spring:
  application:
    name: Nomadly

  datasource:
    url: jdbc:mysql://localhost:3307/nomadly_db
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
