spring:
  application:
    name: Nomadly

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/nomadly_db
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/