spring:
  application:
    name: Nomadly

  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3307/nomadly_db}
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  cloud:
    gateway:
      mvc:
        enabled: true
        headers:
          max-http-header-size: 32KB

server:
  port: ${PORT:8080}
  tomcat:
    max-http-header-size: 32KB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true